---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    pyrax_credentials: ~/.pyrax
    server_basename: openstack-ansible
    git_sha: "{{ lookup('env','OSAD_SHA') }}"
  tasks:

    - name: Build a new cloud server
      action:
        module: rax
        credentials: "{{ pyrax_credentials }}"
        name: "{{ server_basename }}-{{ git_sha }}"
        flavor: general1-8
        image: 09de0a66-3156-48b4-90a5-1cf25a905207
        key_name: jenkins_mhtx_net
        wait: yes
        region: IAD
        state: present
        group: "{{ server_basename }}-{{ git_sha[8:] }}"
        # boot_from_volume: yes
        # boot_volume_size: 200
        # boot_volume_terminate: yes
        networks:
          - public
          - private
        user_data: user_data_osad.yml
      register: rax

    - name: Add new instance to host group
      local_action:
          module: add_host
          hostname: "{{ item.accessIPv4 }}"
          groupname: raxhosts
      with_items: rax.instances

    - name: Wait for server to come online
      wait_for:
        host: "{{ item.accessIPv4 }}"
        port: 22
        delay: 60
        timeout: 500
        state: started
      with_items: rax.instances

- name: Finish
  hosts: raxhosts
  user: root
  tasks:

    - name: Add personal ssh key
      authorized_key:
        user: root
        key: "{{ item }}"
        state: present
        exclusive: no
      with_file:
        - personal_servers.pub

    - name: Wait for OSAD deploy to finish (max 2 hours)
      wait_for:
        path: /var/log/cloud-init-output.log
        search_regex: "OSAD-DEPLOYMENT-COMPLETE"
        timeout: 7200

    # - name: Power off server
    #   command: shutdown -h now
    #   ignore_errors: true
