#cloud-config
apt_mirror: http://iad.mirror.rackspace.com/ubuntu/
package_upgrade: true
packages:
  - git-core
  - screen
  - tmux
runcmd:
  - git clone https://github.com/openstack/openstack-ansible.git /opt/openstack-ansible
  - cd /opt/openstack-ansible && scripts/bootstrap-aio.sh
  - cd /opt/openstack-ansible && scripts/bootstrap-ansible.sh
  - cd /opt/openstack-ansible && time scripts/run-playbooks.sh
  - echo "OSAD-DEPLOYMENT-COMPLETE"
output: { all: '| tee -a /var/log/cloud-init-output.log' }
